---
kind: pipeline
type: docker
name: Build and Push Docker Image

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
  - name: docker-build-push
    image: plugins/docker
    volumes:
      - name: dockersock
        path: "/var/run/docker.sock"
    settings:
      registry: hub.qmcmc.cn
      repo: qcmc/mc-sign
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./Dockerfile
      tags: latest
    when:
      event: push
      branch:
        - master
        - CI
